# ST2195 Practice Assignment 02

## Install Library and Packages

In [8]:
%pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\shani\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\shani\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Note: you may need to restart the kernel to use updated packages.

In [59]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

## Website

In [14]:
URL = "https://www.sim.edu.sg/"
page = requests.get(URL)
page.text

'\r\n\r\n\r\n\r\n<!DOCTYPE html>\r\n\r\n<html lang="en">\r\n<head id="head">\r\n    <meta charset="UTF-8" />\r\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">\r\n    <meta name="apple-mobile-web-app-capable" content="yes">\r\n    <meta http-equiv="x-ua-compatible" content="IE=Edge">\r\n    <meta name="theme-color" content="#000000">\r\n\r\n\r\n\r\n            <meta name="google-site-verification" content="9yOj9DUvrJ_NPSQqyGyhL4i6onHEAbvF9cRtFCk5bys" />\r\n\r\n\r\n            <title>Singapore Institute of Management | Degree &amp; Diploma Programmes | Professional Short Courses</title>\r\n            <meta name="keywords" content="sim, singapore institute of management, degree and diploma, short courses" />\r\n            <meta name="description" content="Singapore Institute of Management offers academic programmes and short courses to help individuals and businesses respond to a rapidly changing world." />\r\n            <meta property="og:site_name" content="Singapore Institute of Management (SIM)" />\r\n            <meta property="og:title" content="Singapore Institute of Management | Degree &amp; Diploma Programmes | Professional Short Courses" />\r\n            <meta property="og:type" content="website" />\r\n            <meta property="og:url" content="https://www.sim.edu.sg/" />\r\n            <meta property="og:description" content="Singapore Institute of Management offers academic programmes and short courses to help individuals and businesses respond to a rapidly changing world." />\r\n            <meta property="og:image" content="https://onesim-production.s3.ap-southeast-1.amazonaws.com/onesim/media/sim-homepage/og%20image/sim-ge-og.jpg?ext=.jpg" />\r\n            <meta property="og:image:secure_url" content="https://onesim-production.s3.ap-southeast-1.amazonaws.com/onesim/media/sim-homepage/og%20image/sim-ge-og.jpg?ext=.jpg" />\r\n\r\n    <link rel="canonical" href="https://www.sim.edu.sg/" />\r\n    <link rel="alternate" href="https://www.sim.edu.sg/" hreflang="en">\r\n    <link rel="icon" type="image/png" href="/Content/Images/favicon.png">\r\n    <link rel="apple-touch-icon" href="/Content/Images/favicon.png">\r\n    <link href="/Content/Styles/main.css?v=FV20mr2Sy-NiQCLT1aGuwjfgKVl9ytONun0cuYYci9c" rel="stylesheet" type="text/css" />\r\n\r\n        <link href="/Content/Bundles/Public/pageComponents.css?v=0A1lNdS6qzUF4zJXcJxzqcKLwBrJYEwBZHzlA7rvaWk" rel="stylesheet" type="text/css" />\r\n    \r\n        <script type="text/javascript" async src="//cdn.evgnet.com/beacon/simedu/sim_local/scripts/evergage.min.js"></script>\r\n    \r\n<script>\r\n    window.dataLayer = window.dataLayer || [];\r\n    dataLayer.push({\r\n        \'event\': \'Pageview\',\r\n        \'pagePath\': \'https://www.sim.edu.sg/\',\r\n        \'pageTitle\': \'Home\'\r\n        \r\n    });\r\n</script>\r\n<!-- Google Tag Manager -->\r\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\r\n        new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\r\n        j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\r\n        \'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\r\n})(window,document,\'script\',\'dataLayer\',\'GTM-T8TBJFH\');</script>\r\n<!-- End Google Tag Manager -->\r\n\r\n\n                              <script>!function(e){var n="https://s.go-mpulse.net/boomerang/";if("False"=="True")e.BOOMR_config=e.BOOMR_config||{},e.BOOMR_config.PageParams=e.BOOMR_config.PageParams||{},e.BOOMR_config.PageParams.pci=!0,n="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="NRDPN-VMD88-LWJHQ-VR8K8-YBQ3M",function(){function e(){if(!o){var e=document.createElement("script");e.id="boomr-scr-as",e.src=window.BOOMR.url,e.async=!0,i.parentNode.appendChild(e),o=!0}}function t(e){o=!0;var n,t,a,r,d=document,O=window;if(window.BOOMR.snippetMethod=e?"if":"i",t=function(e,n){var t=d.createElement("script");t.id=n||"boomr-if-as",t.src=window.BOOMR.url,BOOMR_lstart=(new Date).getTime(),e=e||d.body,e.appendChild(t)},!window.addEventListener&&window.attachEvent&&navigator.userAgent.match(/MSIE [67]\\./))return window.BOOMR.snippetMethod="s",void t(i.parentNode,"boomr-async");a=document.createElement("IFRAME"),a.src="about:blank",a.title="",a.role="presentation",a.loading="eager",r=(a.frameElement||a).style,r.width=0,r.height=0,r.border=0,r.display="none",i.parentNode.appendChild(a);try{O=a.contentWindow,d=O.document.open()}catch(_){n=document.domain,a.src="javascript:var d=document.open();d.domain=\'"+n+"\';void(0);",O=a.contentWindow,d=O.document.open()}if(n)d._boomrl=function(){this.domain=n,t()},d.write("<bo"+"dy onload=\'document._boomrl();\'>");else if(O._boomrl=function(){t()},O.addEventListener)O.addEventListener("load",O._boomrl,!1);else if(O.attachEvent)O.attachEvent("onload",O._boomrl);d.close()}function a(e){window.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!window.BOOMR||!window.BOOMR.version&&!window.BOOMR.snippetExecuted){window.BOOMR=window.BOOMR||{},window.BOOMR.snippetStart=(new Date).getTime(),window.BOOMR.snippetExecuted=!0,window.BOOMR.snippetVersion=12,window.BOOMR.url=n+"NRDPN-VMD88-LWJHQ-VR8K8-YBQ3M";var i=document.currentScript||document.getElementsByTagName("script")[0],o=!1,r=document.createElement("link");if(r.relList&&"function"==typeof r.relList.supports&&r.relList.supports("preload")&&"as"in r)window.BOOMR.snippetMethod="p",r.href=window.BOOMR.url,r.rel="preload",r.as="script",r.addEventListener("load",e),r.addEventListener("error",function(){t(!0)}),setTimeout(function(){if(!o)t(!0)},3e3),BOOMR_lstart=(new Date).getTime(),i.parentNode.appendChild(r);else t(!1);if(window.addEventListener)window.addEventListener("load",a,!1);else if(window.attachEvent)window.attachEvent("onload",a)}}(),"".length>0)if(e&&"performance"in e&&e.performance&&"function"==typeof e.performance.setResourceTimingBufferSize)e.performance.setResourceTimingBufferSize();!function(){if(BOOMR=e.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var n=""=="true"?1:0,t="",a="zpm3wiaxgz3cg2invsnq-f-b8674c026-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,o={"ak.v":"39","ak.cp":"1346910","ak.ai":parseInt("811682",10),"ak.ol":"0","ak.cr":90,"ak.ipv":4,"ak.proto":"http/1.1","ak.rid":"e6c7267","ak.r":47817,"ak.a2":n,"ak.m":"dscb","ak.n":"essl","ak.bpcip":"203.217.187.0","ak.cport":62913,"ak.gh":"23.54.124.195","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.0rtt.ed":"","ak.csrc":"-","ak.acc":"bbr","ak.t":"1762503835","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==S3sFc1TneVkLN8Ut1DRl3GLVaG0iIhYGnbLeZrbJR80z7fUwiBNpasXFT50SBqkvC3+XBuo03uggne6Z5F8OjfGicwpAoL5Lb49bDppK7W2nQiPFtopTAPwtI9YKP5eG/AMMh/K2xLy00rAke6X6tV5WtAWjAm/JgNXNTJGvMtJSfQjCjDyF+jKDttOHUSmAdDjLuWXploD05LWoTSGfBXtxS2YFEzcJER8y6K/damFQfoVVXYKUjssFzUbYuzrPZMkKDfC6hJHeLy7vRDpEaN2Zw5+LiNqALGfEQgMohv9BdvY6pCVzBeA5da0i4FpWKYiMdmIvItWHd/nDm2WZn12KrLLbcY1c49bRZChTl7Ww+X23FelStyy/vwgurkcH9vQOQscfct4AC4KE78oG+dXpYptOtXuqc0w4GKMH89E=","ak.pv":"5","ak.dpoabenc":"","ak.tf":i};if(""!==t)o["ak.ruds"]=t;var r={i:!1,av:function(n){var t="http.initiator";if(n&&(!n[t]||"spa_hard"===n[t]))o["ak.feo"]=void 0!==e.aFeoApplied?1:0,BOOMR.addVar(o)},rv:function(){var e=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.0rtt.ed","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(e)}};BOOMR.plugins.AK={akVars:o,akDNSPreFetchDomain:a,init:function(){if(!r.i){var e=BOOMR.subscribe;e("before_beacon",r.av,null,null),e("onbeacon",r.rv,null,null),r.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>\r\n<body>\r\n        <!-- Google Tag Manager (noscript) -->\r\n    <noscript>\r\n        <iframe title="iFrameGtm" src="https://www.googletagmanager.com/ns.html?id=GTM-T8TBJFH" height="0" width="0" style="display:none;visibility:hidden"></iframe>\r\n    </noscript>\r\n    <!-- End Google Tag Manager (noscript) -->\r\n\r\n    <!-- header component -->\r\n    \r\n\r\n\r\n\r\n\r\n<!-- header component -->\r\n<header class="navbar fixed-top">\r\n    <div class="container-xxl d-flex flex-row flex-nowrap">\r\n\r\n            <div class="logo-container" id="header_logoContainer">\r\n        <a href="\\" class="d-flex align-items-center me-lg-auto text-dark text-decoration-none">\r\n            <img src="https://onesim-production.s3.ap-southeast-1.amazonaws.com/onesim/media/sim-homepage/header logos/sim-logo-2023.svg?ext=.svg" alt="Singapore Institute of Management" width="166" height="50" />\r\n        </a>\r\n    </div>\r\n\r\n\r\n        <div class="mobile-menu-toggle d-lg-none">\r\n            <div class="close-icon">\r\n                <input type="checkbox" />\r\n                <span></span>\r\n                <span></span>\r\n                <span></span>\r\n            </div>\r\n        </div>\r\n\r\n        <div class="nav-scroll" id="header_navWrapper">\r\n            <nav class="nav-wrapper d-lg-block animate-right">\r\n                \r\n\r\n    <ul class="nav mobile-pop-items d-lg-none">\r\n            <li class="nav-item">\r\n                <a class="nav-link link-external" href="https://applytostudy.simge.edu.sg/OAM/" target="_blank">Apply for Degree or Diploma</a>\r\n            </li>\r\n            <li class="nav-item">\r\n                <a class="nav-link link-external" href="https://simdigital.my.site.com/s/login/SelfRegister" target="_blank">Register for Professional Development Course</a>\r\n            </li>\r\n        <li>\r\n            <div class="search-box">\r\n                <!-- redirect URL for search result page shouldn\'t be in JS -->\r\n                <div class="search-box-wrapper" data-redirect-url="/search-results">\r\n                    <button class="btn btn-primary sb-search-btn">\r\n                        <svg xmlns="http://www.w3.org/2000/svg" width="18.164" height="18.017" viewBox="0 0 18.164 18.017">\r\n                            <g id="Group_1795" data-name="Group 1795" transform="translate(-185.75 -36.972)">\r\n                                <path id="Path_521" data-name="Path 521"\r\n                                      d="M193.885,52.242a7.135,7.135,0,1,1,7.135-7.135A7.143,7.143,0,0,1,193.885,52.242Z" fill="none"\r\n                                      stroke="#fff" stroke-linejoin="round" stroke-width="2" />\r\n                                <line id="Line_1" data-name="Line 1" x2="4.014" y2="3.568" transform="translate(199.236 50.674)" fill="none"\r\n                                      stroke="#fff" stroke-linejoin="round" stroke-width="2" />\r\n                            </g>\r\n                        </svg>\r\n                    </button>\r\n                    <input type="text" class="form-control" placeholder="Search..." />\r\n                </div>\r\n            </div>\r\n        </li>\r\n    </ul>\r\n\r\n\r\n\r\n\r\n\r\n\r\n                \r\n    <ul class="nav sub-nav">\r\n                <li class="nav-item">\r\n                    <a href="https://www.sim.edu.sg/thought-leadership"\r\n                       target="_self" class="nav-link ">\r\n                        Thought Leadership\r\n                    </a>\r\n                </li>\r\n                <li class="nav-item">\r\n                    <a href="https://www.sim.edu.sg/news-events"\r\n                       target="_self" class="nav-link ">\r\n                        News &amp; Events\r\n                    </a>\r\n                </li>\r\n                <li class="nav-item">\r\n                    <a href="https://www.sim.edu.sg/articles-inspirations"\r\n                       target="_self" class="nav-link ">\r\n                        Articles &amp; Inspirations\r\n                    </a>\r\n                </li>\r\n                <li class="nav-item">\r\n                    <a href="https://library.sim.edu.sg"\r\n                       target="_blank" class="nav-link link-external">\r\n                        Library\r\n                    </a>\r\n                </li>\r\n                <li class="nav-item dropdown">\r\n                    <a href="/"\r\n                       target="_blank" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">\r\n                        Learners&#x2019; Login\r\n                    </a>\r\n                    <ul class="dropdown-menu dropdown-menu-end">\r\n                            <li>\r\n                                <a href="https://applytostudy.simge.edu.sg/"\r\n                                   target="_blank"\r\n                                   class="dropdown-item link-external">\r\n                                    SIMConnect Portal\r\n                                </a>\r\n                            </li>\r\n                            <li>\r\n                                <a href="https://simdigital.my.site.com/s/login"\r\n                                   target="_blank"\r\n                                   class="dropdown-item link-external">\r\n                                    SIM Online\r\n                                </a>\r\n                            </li>\r\n                            <li>\r\n                                <a href="https://www.sim.edu.sg/degrees-diplomas/life-at-sim/career-services"\r\n                                   target="_blank"\r\n                                   class="dropdown-item link-external">\r\n                                    CareerSense\r\n                                </a>\r\n                            </li>\r\n                            <li>\r\n                                <a href="https://onlinelearn.sim.edu.sg/"\r\n                                   target="_self"\r\n                                   class="dropdown-item link-external">\r\n                                    SIM Canvas\r\n                                </a>\r\n                            </li>\r\n                    </ul>\r\n\r\n                </li>\r\n                <li class="nav-item">\r\n                    <a href="/alumni"\r\n                       target="_self" class="nav-link ">\r\n                        Alumni\r\n                    </a>\r\n                </li>\r\n                <li class="nav-item">\r\n                    <a href="/academics"\r\n                       target="_self" class="nav-link ">\r\n                        Academics\r\n                    </a>\r\n                </li>\r\n                <li class="nav-item">\r\n                    <a href="https://www.sim.edu.sg/contact-us"\r\n                       target="_self" class="nav-link ">\r\n                        Contact Us\r\n                    </a>\r\n                </li>\r\n    </ul>\r\n\r\n\r\n\r\n                    <ul class="nav main-nav">\r\n                            <li class="nav-item dropdown dropdown-mega">\r\n                                <a class="nav-link" data-mega-menu-level="0" data-mega-menu-index="0" data-mega-id="megamenu-0">\r\n                                    SIM60<i class="arrow arrow-right d-lg-none"></i>\r\n                                </a>\r\n                                    <div class="dropdown-menu" data-mega-id="megamenu-0">\r\n                                        <div class="mega-menu-column">\r\n                                            <div class="mobile-menu-header d-lg-none">\r\n                                                <span><i class="arrow arrow-left"></i>SIM60</span>\r\n                                            </div>\r\n                                            <ul data-mega-menu-level="1">\r\n                                                        <li>\r\n\r\n                                                                <a href="https://www.sim.edu.sg/sim60/landingpage"\r\n                                                                   target="_self"\r\n                                                                   class=""\r\n                                                                >\r\n                                                                    Overview \r\n                                                                </a>\r\n\r\n                                                        </li>\r\n                                            </ul>\r\n                                        </div>\r\n                                    </div>\r\n\r\n                            </li>\r\n                            <li class="nav-item dropdown dropdown-mega">\r\n                                <a class="nav-link" data-mega-menu-level="0" data-mega-menu-index="1" data-mega-id="megamenu-1">\r\n                                    Degrees &amp; Diplomas<i class="arrow arrow-right d-lg-none"></i>\r\n                                </a>\r\n                                    <div class="dropdown-menu" data-mega-id="megamenu-1">\r\n                                        <div class="mega-menu-column">\r\n                                            <div class="mobile-menu-header d-lg-none">\r\n                                                <span><i class="arrow arrow-left"></i>Degrees &amp; Diplomas</span>\r\n                                            </div>\r\n                                            <ul data-mega-menu-level="1">\r\n                                                        <li>\r\n\r\n                                                                <a href="https://www.sim.edu.sg/degrees-diplomas/overview"\r\n                                                                   target="_self"\r\n                                                                   class=""\r\n                                                                >\r\n                                                                    Overview \r\n                                                                </a>\r\n\r\n                                                        </li>\r\n                                                        <li>\r\n\r\n                                                                <span class=""\r\n                                                                data-sub-menu-toggle=\'menu\'>\r\n                                                                    SIM Global Education <i class=\'arrow arrow-right\'></i>\r\n                                                                </span>\r\n\r\n                                                                <div class="next-level">\r\n                                                                    <div class="mobile-menu-header d-lg-none">\r\n                                                                        <span><i class="arrow arrow-left"></i>SIM Global Education</span>\r\n                                                                    </div>\r\n                                                                    <ul data-mega-menu-level="2">\r\n                                                                            <li>\r\n                                                                                    <a href="https://www.sim.edu.sg/degrees-diplomas/sim-global-education/sim-advantage"\r\n                                                                                       target="_self"\r\n                                                                                       class=""\r\n                                                                                    >\r\n                                                                                        The SIM Advantage \r\n                                                                                    </a>\r\n\r\n\r\n\r\n                                                                            </li>\r\n                                                                            <li>\r\n                                                                                    <a href="https://

### Webscrapping

#### Getting text of html

In [21]:
soup = BeautifulSoup(page.text, 'html.parser')

#### Locate Contact Information

In [32]:
footer = soup.find('footer')
spans = footer.find_all('span')
spans

[<span>Email: </span>,
 <span> <a href="mailto:study@sim.edu.sg">study@sim.edu.sg</a> </span>,
 <span>Phone: </span>,
 <span> <a href="tel:6248 9746">6248 9746</a><br/>
 <span class="font-small">(Mon to Fri, 9.00am - 5.00pm)<br/>
 (Closed on Sat, Sun, public holidays and SIM shutdown days - Christmas Eve, New Year’s Day Eve and Chinese New Year Eve, 3rd day of Chinese New Year)</span></span>,
 <span class="font-small">(Mon to Fri, 9.00am - 5.00pm)<br/>
 (Closed on Sat, Sun, public holidays and SIM shutdown days - Christmas Eve, New Year’s Day Eve and Chinese New Year Eve, 3rd day of Chinese New Year)</span>,
 <span>Address: </span>,
 <span>461 Clementi Road, Singapore 599491<br/>
 <span class="font-small">(Daily except public holidays, 6am to 11.59pm)</span><br/>
 <a href="https://g.page/simglobaleducation?share" target="_blank">Getting here</a></span>,
 <span class="font-small">(Daily except public holidays, 6am to 11.59pm)</span>,
 <span>Email: </span>,
 <span> <a href="mailto:simacademy@sim.edu.sg">simacademy@sim.edu.sg</a> </span>,
 <span>Address: </span>,
 <span>41 Namly Avenue, Singapore 267616<br/>
 <span class="font-small">Mon- Fri (8.30am – 5.30pm)<br/>
 (Closed on Sat, Sun, public holidays and SIM shutdown days) <!--(Mon - Sat, 6am - 11pm)<br />
 (Closed on Sun, public holidays and SIM shutdown days)--></span><br/>
 <!-- https://g.page/SIMPDEL?share --><a href="https://goo.gl/maps/R9wwuacutyL8xJgHA" rel="noopener nofollow" target="_blank">Getting here</a></span>,
 <span class="font-small">Mon- Fri (8.30am – 5.30pm)<br/>
 (Closed on Sat, Sun, public holidays and SIM shutdown days) <!--(Mon - Sat, 6am - 11pm)<br />
 (Closed on Sun, public holidays and SIM shutdown days)--></span>,
 <span id="footer-year"></span>,
 <span class="d-none d-lg-inline-block">|</span>,
 <span class="">|</span>,
 <span class="">|</span>]

#### Cleaning Retrieved Contact Information

In [50]:
index = 0
email_lst = []
phone_lst = []
address_lst = []

for span in spans:
    if ("Email" in span.text):
        email = spans[index+1].text
        email = email.strip()
        email_lst.append(email)

    if("Phone" in span.text):
        phone = spans[index+1].text

        # 8 Number + 1 Space = 9 Characters
        phone = phone [:10]
        phone = phone.strip()
        phone_lst.append(phone)

    if("Address" in span.text):
        address = spans[index+1].text
        address_end = address.find("\n")
        address = address[:address_end]
        address = address.strip()
        address_lst.append(address)

    index += 1

In [65]:
print(email_lst)
phone_lst.append("") ## To deal with the different length
print(phone_lst)
print(address_lst)

['study@sim.edu.sg', 'simacademy@sim.edu.sg']
['6248 9746', '']
['461 Clementi Road, Singapore 599491', '41 Namly Avenue, Singapore 267616']

#### Create Contact Dictionary

In [68]:
contact_dict = {'Email': email_lst, 'Phone': phone_lst, 'Address': address_lst}
contact_dict

{'Email': ['study@sim.edu.sg', 'simacademy@sim.edu.sg'],
 'Phone': ['6248 9746', ''],
 'Address': ['461 Clementi Road, Singapore 599491',
  '41 Namly Avenue, Singapore 267616']}

#### Create Data Frame

In [71]:
contact_df = pd.DataFrame(contact_dict)
contact_df

                   Email      Phone                              Address
0       study@sim.edu.sg  6248 9746  461 Clementi Road, Singapore 599491
1  simacademy@sim.edu.sg               41 Namly Avenue, Singapore 267616

#### Save to CSV File

In [80]:
contact_df.to_csv("contact.csv", index=False, header=True)

##### Check File Exists and Has Contact Information

In [85]:
contacts = pd.read_csv("contact.csv")
contacts

                   Email      Phone                              Address
0       study@sim.edu.sg  6248 9746  461 Clementi Road, Singapore 599491
1  simacademy@sim.edu.sg        NaN    41 Namly Avenue, Singapore 267616